FROM node:24-alpine

RUN corepack enable && corepack prepare pnpm@9.15.2 --activate

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

RUN apk add --no-cache \
    git \
    python3 \
    make \
    g++

USER node

WORKDIR /app

EXPOSE 3000
EXPOSE 24678

CMD ["sh", "-c", "pnpm install && pnpm dev"]